# Generated by Django 3.1.6 on 2021-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(blank=True, choices=[('RU', 'Russian'), ('AZ', 'Azerbajan'), ('FR', 'France'), ('ENG', 'English'), ('USA', 'United states')], max_length=3, null=True),
        ),
    ]
