# Generated by Django 3.1.7 on 2021-04-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210330_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlicense',
            old_name='number_id',
            new_name='number',
        ),
    ]
